services:
  backend:
    image: mkuziv/bigshare-back:latest
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bigshare
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: new_password
    ports:
      - "8081:8081"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: mkuziv/bigshare-database:latest
    environment:
      MYSQL_ROOT_PASSWORD: new_password
      MYSQL_DATABASE: bigshare
    ports:
      - "3306:3306"
    networks:
      - app-network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pnew_password"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

networks:
  app-network:
    driver: bridge
