jwt:
  auth:
    secret_key: testkey#secret@12334
    expires_in: '3600'
    app: Spring-Security-App
spring:
  datasource:
    username: ${MYSQL_USER:admin}
    url: jdbc:mysql://${MYSQL_HOST:bigshare-mysql.cj004s8c8232.eu-north-1.rds.amazonaws.com}:${MYSQL_PORT:5432}/${MYSQL_DATABASE:bigshare_db}
    password: ${MYSQL_PASSWORD:new_password}
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: 'true'
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
server:
  port: ${PORT:8083}

