jwt:
  auth:
    secret_key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expires_in: '36000'
    app: Spring-Security-App
spring:
  datasource:
    username: ${MYSQL_USER:admin}
    url: jdbc:mysql://${MYSQL_HOST:bigshare-mysql.cnm6saymschf.eu-north-1.rds.amazonaws.com}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:bigshare_db}?createDatabaseIfNotExist=true
#    docker run -p 8090:8081 --name bigshare-api-container --net bigshare-network -e MYSQL_HOST=bigshare-mysql -e MYSQL_USER=root -e MYSQL_PASSWORD=new_password -e MYSQL_PORT=3306 -e MYSQL_DATABASE=bigshare mkuziv/bigshare-backend
    password: ${MYSQL_PASSWORD:new_password}
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: 'true'
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
server:
  port: ${PORT:8083}

