jwt:
  auth:
    secret_key: testkey#secret@12334
    expires_in: '3600'
    app: Spring-Security-App
spring:
  datasource:
    username: ${MYSQL_USER:root}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:bigshare}
    password: ${MYSQL_PASSWORD:new_password}
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: 'true'
server:
  port: ${PORT:8081}
